apiVersion: v1
kind: Pod
metadata:
  name: hello-web-pod
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: task-pv-claim
  containers:
    - name: hello-web-container
      image: gcr.io/startup-194601/github-jackliuangel-hello-web:2.0
      volumeMounts:
        - mountPath: "/tmp/share"
          name: task-pv-storage

      env:
        # Define the environment variable
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              # The ConfigMap containing the value you want to assign to SPECIAL_LEVEL_KEY
              name: special-config
              # Specify the key associated with the value
              key: special.how
  restartPolicy: Never
